module.exports = {
  content: [
    "./resources/**/*.blade.php",
    "./resources/**/*.js",
    "./resources/**/*.vue",
  ],
  safelist: [
    // Classes du header qui doivent TOUJOURS être incluses
    'flex',
    'items-center',
    'justify-between',
    'space-x-3',
    'gap-2',
    'px-3',
    'py-2',
    'rounded-lg',
    'hover:bg-gray-100',
    'text-gray-700',
    'font-medium',
    'truncate',
    'max-w-7xl',
    'mx-auto',
    'border',
    'bg-white',
    'shadow-md',
    'w-8',
    'h-8',
    'rounded-full',
    'bg-center',
    'bg-cover',
    'text-sm',
    'absolute',
    'right-0',
    'mt-2',
    'w-64',
    'border-gray-200',
    'rounded-2xl',
    'shadow-xl',
    'overflow-hidden',
    'z-50',
    'p-3',
    'border-b',
    'min-w-0',
    'font-semibold',
    'mb-1',
    'text-xs',
    'inline-flex',
    'gap-1.5',
    'px-2.5',
    'py-0.5',
    'bg-emerald-100',
    'text-emerald-700',
    'ring-1',
    'ring-emerald-600/20',
    'max-w-[10rem]',
    'max-w-[12rem]',
    'py-1',
    'px-4',
    'py-2.5',
    'hover:bg-gray-50',
    'mt-1',
    'w-full',
    'text-left',
    'text-red-600',
    'hover:bg-red-50',
    'relative',
    'hidden',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}